[build.environment]
  NODE_VERSION = "20"

[build]
  publish = "dist"
  command = "bun run build"

[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
